apiVersion: v1
data:
  MYSQL_REPLICATION_MODE: master
  MYSQL_REPLICATION_USER: repl_user
  MYSQL_REPLICATION_PASSWORD: repl_password
  MYSQL_ROOT_PASSWORD: master_root_password
  MYSQL_USER: my_user
  MYSQL_PASSWORD: my_password
  MYSQL_DATABASE: my_database
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-config-master
---
apiVersion: v1
data:
  MYSQL_REPLICATION_MODE: slave
  MYSQL_REPLICATION_USER: repl_user
  MYSQL_REPLICATION_PASSWORD: repl_password
  MYSQL_MASTER_HOST: mysql-master
  MYSQL_MASTER_PORT_NUMBER: "3306"
  MYSQL_MASTER_ROOT_PASSWORD: master_root_password
kind: ConfigMap
metadata:
  creationTimestamp: 
  name: mysql-config-slave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql-master
  name: mysql-master
spec:
  replicas: 1
  serviceName: mysql-master
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
      - image: bitnami/mysql
        name: mysql
        envFrom:
        - configMapRef:
            name: mysql-config-master
        volumeMounts:
        - name: mysql-master-pvc
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-master-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql-slave
  name: mysql-slave
spec:
  replicas: 1
  serviceName: mysql-slave
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata: 
      labels:
        app: mysql-slave
    spec:
      containers:
      - image: bitnami/mysql
        name: mysql
        envFrom:
        - configMapRef:
            name: mysql-config-slave
        volumeMounts:
        - name: mysql-slave-pvc
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-slave-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    app: mysql-master
spec:
  ports:
  - port: 3306
    name: http
  selector:
    app: mysql-master
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    app: mysql-slave
spec:
  ports:
  - port: 3306
    name: http
  selector:
    app: mysql-slave
  type: ClusterIP